### ISSUE TITLE
DTR 2020 TB

### ISSUE THREAD

**Issue by TukovitsBalazs** [Teaching-projects/SOE-DTR-2020-Szallitas-Tukovits#1]
Szia!

Kérlek nézd meg a megoldásomat!

Üdv.,
Balázs

**Comment by hegyhati** [comment]
A feladat leirasa nem igazan vilagos. Nem ertheto, hogy most tobbfele alapanyag van, vagy tobb hely van, ahol ugyanabbol az alapanyagbol van tobb. Mit akarunk optimalizalni, az mitol fugg, milyen donteseket hozhatunk meg? Ezeket ertelmes magyar nyelven le kellene irni, mielott kodot mutogatunk.

A readme-ben a kodreszletek ampl szerint legyenek formazva.

A teljese kodot a vegere nem kell bevagni, felesleges, ott van mellette.

A modell utan mar vilagos, hogy ez egy sima szallitasi feladat megpimpelve azzal, hogy van ez a kuszobertek feletti olcsobb szallitas. BigM-ek rendben, ennek is orulok.  A leirast mindenkeppen rendbe kell tenni, illetve kerdes az, hogy milyen jegyet szeretnel kapni. Feltetelezem 4-5, ezert mondok dolgokat, amiknek meg orulnek a fentieken kivul:
 - erzekenysegvizsgalat: hogy valtozik a dolog, ha a csokkentett ar csokken, vagy a limitje csokken, stb.
 - otoshoz meg valamit kellene azert bonyolitani ezen. Vagy tobb napra tervezni, es vannak mondjukj hataridok, vagy vannak kulonbozo alapanyagok, vagy a kamionoknak van kapacitasa, stb.

**Comment by TukovitsBalazs** [comment]
Köszönöm a visszajelzést!

Igen, egy 4-esnek nagyon örülnék. Szeretnék a zv-re készülni teljes erőbedobással, a tételeket is hamarosan kidolgozom és elküldöm.

Átírtam a leírást, a kódot és hozzáadtam egy érzékenység vizsgálatot. Az érzékenység vizsgálattal ilyenre gondoltál?
Kellene még valamit módosítanom rajta?

**Comment by hegyhati** [comment]
Erdemi valtozas nem tortent. 

Az ampl formazas ilyen:
```ampl
var x;
```
A harom backtick utan tessek beirni, hogy `ampl`, preview-ban latod, hogy ott van-e a syntax highlight.

A negyes meglenne az erzekenysegvizsgalattal. Az viszont nem 3 mese-matka mondat, hanem tenyleg meg kellene csinalni az erzekenysegvizsgalatot, azaz fogj pl egy parametert, kezd el vizsgalni, hogy mi van akkor , ha az adott mennyiseg folotti szallitas ugyanannyiba kerul, 5%-kal olcsobb, 10%-kal olcsobb, stb... akkor hogy valtozik az optimum erteke. Es meg lehet nezni az 5%-kal dragabb, 10%-kal dragabb dolgot is. Legalabb 10 parameterertekre futtatod a modellt, feljegyzed az optimumot, csinalsz belole egy szep diagrammot, ahol x tengelyen van a normal / extra szallitasi koltseg aranya, 7 tengelyen a megtalalt optimum.

**Comment by TukovitsBalazs** [comment]
Megtörténtek a változtatások.

A diagramot egy külön PDF-ként töltöttem fel. Megvizsgáltam 85, 90, 95 és 100-as küszöbértékre, a kedvezmény értékeket pedig 15, 20, 25, 30, 35%-ra is beállítottam.

**Comment by hegyhati** [comment]
No, rendben  lesz ez, be fogom irni a 4-est, de, akkor most szedjuk rancba a repot.
 - ne kulon pdf legyen. legyen kep, es legyen berakva az md-be. 
 - az md legyen atnevezve Readme.md-re, hogy rogton megjelenjen amikor valaki ramegy a repora
 - az erzekenysegvizsgalatnal ird is le, hogy mit csinaltal, illetve nem tudom, hogy ez-e a leglatvanyosabb vizualizacioja a dolognak. Mivel ket parametert is mozgattal, lehet az egyiket x-re, masikat y-ra tennem, es az optimumot z-re. De ez csak otlet.
 
Ezeket raersz megcsinalni, csak legyenek majd meg.

**Comment by hegyhati** [comment]
Jah, es vizsgaval nincs dolgod, beirom a 4-est es kesz.
